# https://circleci.com/docs/2.1/language-javascript/
version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: update npm
          command: sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: extract version
          command: |
            VERSION=$(head -n1 CHANGELOG.md | grep -o '\([0-9]\+\.\)\{2\}[0-9]\+')
            echo "export VERSION=${VERSION}" >> $BASH_ENV
            echo "building version: ${VERSION}"
  bundle-test-setup:
    steps:
      - attach_workspace:
          at: ~/google-optimize-service
      - run:
          name: create test application
          command: |
            mkdir test-app
            cd test-app
            npm init -y
      - run:
          name: install module
          command: |
            npm i -S ~/google-optimize-service


workflows:
  version: 2
  test:
    when: always
    jobs:
      - lint
      - test
      - bundle:
          requires:
            - lint
            - test
      - bundle-test-node-js:
          requires:
            - bundle
      - bundle-test-esm-js:
          requires:
            - bundle

jobs:
  lint:
    docker:
      - image: circleci/node:lts
    working_directory: ~/google-optimize-service
    steps:
      - setup
      - run:
          name: create test-results-folder
          command: mkdir -p test-results/eslint
      - run:
          name: lint
          command: npm run lint:ci
      - store_test_results:
          path: test-results

  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/google-optimize-service
    steps:
      - setup
      - run:
          name: unit tests
          command: npm run test:ci
      - store_test_results:
          path: test-results

  bundle:
    docker:
      - image: circleci/node:lts
    working_directory: ~/google-optimize-service
    steps:
      - setup
      - run:
          name: bundle
          environment:
            NODE_ENV: 'production'
          command: npm run build
      - store_artifacts:
          path: lib
      - persist_to_workspace:
          root: ./
          paths:
            - lib
            - src/package-tests
            - package.json

  bundle-test-node-js:
    docker:
      - image: circleci/node:lts
    working_directory: /tmp
    steps:
      - bundle-test-setup
      - run:
          name: test node.js module
          command: |
            cp ~/google-optimize-service/src/package-tests/node/node.test.js ./
            node node.test.js

  bundle-test-esm-js:
    docker:
      - image: circleci/node:lts
    working_directory: /tmp
    steps:
      - bundle-test-setup
      - run:
          name: copy test
          command: |
            cp ~/google-optimize-service/src/package-tests/esm/* ./
      - run:
          name: install dependencies
          command: |
            npm i
      - run:
          name: test esm.js module
          command: |
            npm test
      - store_test_results:
          path: test-results
